#!/bin/bash 
commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

if ! echo "$commit_msg" | grep -q "^PB412780"; then
    echo >&2 "Błąd: Commit musi zaczynać się od: PB412780"
    exit 1
fi

exit 0