#!/bin/bash 
commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

if ! echo "$commit_msg" | grep -q "^KR409837"; then
    echo >&2 "Błąd: Commit musi zaczynać się od: KR409837"
    exit 1
fi

exit 0