apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-clock-deployment-canary
  labels:
    app: nginx-clock
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-clock
      track: canary
  template:
    metadata:
      labels:
        app: nginx-clock
        track: canary
    spec:
      containers:
      - name: nginx-clock
        image: krystian3243/nginx-clock:1.1
        ports:
        - containerPort: 80