- name: FullPlaybook
  hosts: Endpoints
  remote_user: oversear
  become: yes

  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Copy file with permit
      ansible.builtin.copy:
        src: ./inventory.ini
        dest: /home/ansible/inventory.ini
        owner: ansible
        group: ansible
        mode: u=rw,g=r,o=r

    - name: Update packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted