FROM fedora

RUN dnf install -y git wget make gcc tcl tcl-devel tk procps which zip && \
    git clone -b 7.2 --single-branch https://github.com/redis/redis.git
    
WORKDIR /redis

RUN make distclean & make