#!/usr/bin/env python3
import sys

COMMIT_MSG = "[JK412625]"

def check_format(commit_msg: str) -> bool:
    return True if commit_msg.startswith(COMMIT_MSG) else False


def read_commit_msg_file(filename: str) -> str:
    with open(filename, 'r') as f:
        commit_msg = f.read()
    return commit_msg


if __name__ == "__main__":
    commit_msg = read_commit_msg_file(sys.argv[1])
    if not check_format(commit_msg):
        raise Exception(f"\nThe commit message should start with {COMMIT_MSG}\n" \
                             f"not: '{commit_msg[:11]}'")
