#!/bin/bash

commit_msg=$(cat $1)

if [[ ! $commit_msg =~ ^LO410687.*$ ]]; then
    echo "Commit message must start with 'LO410687'."  
    echo "Commit blocked! "  
    exit 1  
fi
echo "Correct commit"
