
pipeline {
    agent any
    environment {
        GIT_REPO = 'https://github.com/DarkRec/sqlite.git'
        GIT_BRANCH = 'main'
        DOCKERHUB_TOKEN = credentials('dockerhub-token')
    }
    stages {
        stage('Prepare') {
            steps {
                script {
                    deleteDir()
                    sh'''
                    git clone ${GIT_REPO}
                    '''
                }
            }
        }
        stage('Build') {
            steps {
                dir("sqlite") {
                    sh 'docker build -t sqlite_builder -f dockerfile_builder .'
                }
            }
        }
        stage('Test') {
            steps {
                dir("sqlite") {
                    sh 'docker build -t sqlite_tester -f dockerfile_tester .'
                }
                
            }
        }
        stage('Deploy') {
            steps {
                dir("sqlite") {
                    sh 'docker build -t sqlite_deploy -f dockerfile_deploy .'
                }
            }
        }
        stage('Smoke Test') {
            steps {
                echo 'Smoke test'
                sh '''
                docker run -it --rm --name deploy_container sqlite_deploy
                '''
            }
        }
        stage('Publish') {
            steps {
                dir("sqlite") {
                    sh '''
                    TIMESTAMP=$(date +%Y%m%d%H%M%S)
                    tar -czf Artifact_$TIMESTAMP.tar.gz dockerfile_builder dockerfile_tester dockerfile_deploy
                    
                    echo $DOCKERHUB_TOKEN_PSW | docker login -u $DOCKERHUB_TOKEN_USR --password-stdin
                    NUMBER='''+ env.BUILD_NUMBER +'''
                    docker tag sqlite_deploy darkrec/sqlite:latest
                    docker push darkrec/sqlite:latest
                    docker logout
                    '''
                    archiveArtifacts artifacts: 'Artifact_*.tar.gz', fingerprint: true
                }
            }
        }
    }
}
