apiVersion: apps/v1
kind: Deployment
metadata:
  name: hot-cold3
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: alexssandrr/react-hot-cold:bug
        ports:
        - containerPort: 3000
