apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-stable
  labels:
    app: my-nginx
    version: stable
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-nginx
      version: stable
  template:
    metadata:
      labels:
        app: my-nginx
        version: stable
    spec:
      containers:
      - name: my-nginx
        image: agnieszka123/my-nginx:1.0.1
        ports:
        - containerPort: 38337