pipeline {
    agent any

    stages {
        stage('Prepare') {
            steps {
                sh 'rm -rf irssi'
                sh 'git clone https://github.com/Grallistrix/irssi'
                dir("MDO2024_INO"){
                    sh 'git checkout DP412497'
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Building'
                sh 'docker images'
                sh 'docker rmi -f irssi-builder'
                sh 'docker images'
                dir('MDO2024_INO/ITE/GCL4/DP412497/Sprawozdanie3'){
                    sh 'docker build -t irssi-builder -f irssi-builder.Dockerfile .'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
                dir('MDO2024_INO/ITE/GCL4/DP412497/Sprawozdanie3'){
                    sh 'docker build -f irssi-tstr.Dockerfile .'
                }
            }
        }
        stage('Publish') {
            steps {
                echo 'Publishing'
                dir('MDO2024_INO/ITE/GCL4/DP412497/Sprawozdanie3'){
                    echo 'RPM'
                    sh 'docker build -t irssi-publisher -f irssi-publish.Dockerfile .'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
                dir('MDO2024_INO/ITE/GCL4/DP412497/Sprawozdanie3'){
                    sh "docker stop irssi-1"
                    sh "docker rm -f irssi-1"
                    sh 'docker build -t irssi-deployer -f irssi-deploy.Dockerfile .'
                    sh "docker run -it -d --name irssi-1 irssi-deployer"
                    sh "docker exec irssi-1 irssi --version"
                    sh "docker logs irssi-1"
                }
            }
        }
        
    }
}