version: '3.8'
services:
   build:
      build:
         context: .
         dockerfile: Dockerfile
      image: app_build
   test:
      build:
         context: .
         dockerfile: Dockerfile2
      image: app_test
      depends_on:
         - build
