apiVersion: apps/v1
kind: Deployment
metadata:
  name: customnginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: custom-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: customnginx
        image: kinga01/custom-nginx:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
