apiVersion: apps/v1
kind: Deployment
metadata:
  name:  game-deploy-rolling-update
  labels:
    app: guess-the-number
spec:
  replicas: 4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 25%
  selector:
    matchLabels:
      app: guess-the-number
  template:
    metadata:
      labels:
        app: guess-the-number
    spec:
      containers:
      - name: guess-the-number
        image: lukoprych/guess-the-number:1.0.2
        ports:
        - containerPort: 80