- name: Deploy
  hosts: Endpoints
  tasks:
    - name: Pull
      docker_image:
        name: flafyking/node-js-dummy-test:1.0.2
        source: pull
    
    - name: Run
      docker_container:
        name: irssi
        image: flafyking/node-js-dummy-test:1.0.2
        state: started
        interactive: yes
        tty: yes