FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y git maven && \
    apt-get clean

RUN git clone https://github.com/jitpack/maven-simple && \
    cd maven-simple && \
    mvn -Dmaven.compiler.source=8 -Dmaven.compiler.target=8 compile