pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                sh '''
                #!/bin/bash
                docker image prune -f
                docker container prune -f
                rm -rf ITE
                '''
                git branch: 'JR412219', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2024_INO.git'
            }
        }
        stage('Build') {
            steps {
                dir('ITE/GCL4/JR412219/Workspace/Lab3/TDWA'){
                    script{
                        def logname = "build_logs_${env.BUILD_NUMBER}.log"
                        sh'''
                        ls
                        docker build -t tdwabuild -f TDWAbuild.Dockerfile . > ${logname}
                        '''
                    }
                }
               
            }
        }
        stage('Test') {
            steps {
                 dir('ITE/GCL4/JR412219/Workspace/Lab3/TDWA'){
                 sh '''
                 #!/bin/bash
                 docker build -t tdwatest -f TDWAtest.Dockerfile . > test_logs_${env.BUILD_NUMBER}
                 '''
                 }
            }
        }
        stage('Deploy') {
            steps {
                 dir('ITE/GCL4/JR412219/Workspace/Lab3/TDWA'){
                 sh '''
                 #!/bin/bash
                 docker build -t tdwadeploy -f TDWAdeploy.Dockerfile . > deploy_logs_${env.BUILD_NUMBER}
                 '''
                 }
            }
        }
        stage('Conection Test') {
            steps {
                script {
                    sh '''
                        #!/bin/bash
                        docker run tdwadeploy . > deploy_logs_${env.BUILD_NUMBER}
                        sleep 5
                        if nc -zv service 3000; then
                            echo 'TDWA is reachable'
                        else
                            echo 'TDWA is not reachable'
                        fi
                        '''
            }
        }
        }
        stage('Publish') {
            steps {
            sh'''
            npm install -g verdaccio
            verdaccio
            npm config set registry http://localhost:4873/
            npm publish --registry http://localhost:4873/
            '''
            }
        }
    }
}