apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-app-recreate
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: clinic-app
      strategy: recreate
  template:
    metadata:
      labels:
        app: clinic-app
        strategy: recreate
    spec:
      containers:
      - name: clinic-app
        image: zuza2828/app-deploy:1.0.0
        ports:
        - containerPort: 8080