apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-app-canary
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: clinic-app
      strategy: canary
  template:
    metadata:
      labels:
        app: clinic-app
        strategy: canary
        version: v1
    spec:
      containers:
      - name: clinic-app
        image: zuza2828/app-deploy:1.0.0
        ports:
        - containerPort: 8080