- name: Ping all machines
  hosts: all
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
- name: Copy inventory
  hosts: Endpoints
  tasks:
   - name: Copy
     copy:
       src: ~/ssh/klucze_ssh/MDO2024_INO/INO/GCL1/AB413227/Sprawozdanie4/inventory.ini
       dest: ~/inventory.ini
- name: Update package
  hosts: Endpoints
  vars:
    ansible_become_pass: ansible # Password is ansible in this case
  tasks:
  - name: update
    become: yes
    apt:
      name: "*"
      state: latest
- name: Restart sshd and rngd
  hosts: Endpoints
  vars:
    ansible_become_pass: ansible
  tasks:
  - name: Restart sshd
    become: yes
    service:
      name: ssh
      state: restarted
  - name: Restart rngd
    become: yes
    service:
      name: rngd
      state: restarted
