- name: Ensure Docker is installed on OpenSUSE
  zypper:
    name: docker
    state: present
  when: ansible_facts['os_family'] == 'Suse'

- name: Ensure Docker service is running and enabled on OpenSUSE
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == 'Suse'
