apiVersion: apps/v1
kind: Deployment
metadata:
  name: utt-deployer-rolling-update
  labels:
    app: utt-deployer
spec:
  replicas: 8
  selector:
    matchLabels:
      app: utt-deployer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 30%
  template:
    metadata:
      labels:
        app: utt-deployer
    spec:
      containers:
      - name: utt-deployer
        image: phisiic/utt-deployer:2.0
        ports:
        - containerPort: 8000
