FROM ubuntu 

RUN apt-get update
RUN apt-get -y install curl
RUN apt-get install -y git

RUN git config --global user.name "barkowalska"
RUN git config --global user.email "j.kowalska971@gmail.com"
RUN git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2024_INO.git


