apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: canary
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-port
      protocol: TCP
      port: 443
      targetPort: 443