#!/usr/bin/env python

import sys
import os
import re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()

start_string = 'MJ410315'

if not branch.startswith(start_string):
    print(f"commit-msg: ERROR! The commit message must start with {start_string}")
    sys.exit(1)