apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-deploy
          image: benek2002/java_deploy:1.0
          ports:
            - containerPort: 8080

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: java-app-service
# spec:
#   selector:
#     app: java-app
#   type: NodePort
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#       nodePort: 30986
