apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-rolling-update
  labels:
    app: java-app
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 50%
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-deploy
          image: benek2002/java_deploy:1.1
          ports:
            - containerPort: 8080

