apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-stable
  labels:
    app: java-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
        version: stable   
    spec:
      containers:
        - name: java-deploy
          image: benek2002/java_deploy:1.0
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-canary
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
      version: canary     
  template:
    metadata:
      labels:
        app: java-app
        version: canary
    spec:
      containers:
        - name: java-deploy
          image: benek2002/java_deploy:1.1   
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
    version: stable
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30986
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-canary-service
spec:
  selector:
    app: java-app
    version: canary
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30987