apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deployment
  labels:
    app: pet-app
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pet-app
      strategy: recreate
  template:
    metadata:
      labels:
        app: pet-app
        strategy: recreate
    spec:
      containers:
      - name: pet-app
        image: radeckimaciej/deploy:1.1.1
        ports:
        - containerPort: 8080
