apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deployment
  labels:
    app: pet-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: pet-app
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
      - name: pet-app
        image: radeckimaciej/deploy:1.1.1
        ports:
        - containerPort: 8080
