- name: Deploy
  hosts: Endpoints
  tasks:
    - name: Pull image
      docker_image:
        name: kogucik1519/my-nginx:0.1
        source: pull
    
    - name: Run
      docker_container:
        name: node
        image: kogucik1519/my-nginx:0.1
        state: started
        interactive: yes
        tty: yes