#!/usr/bin/env python3
import sys
MESSAGE = "JL407285"

def get_message(name):
    with open(name, 'r') as f:
        msg = f.read()
    return msg

msg = get_message(sys.argv[1])
if not msg.startswith(MESSAGE):
    raise Exception(f"\nWanted -> {MESSAGE}\nGot -> {msg}\n")