#!/bin/bash

commit_msg_file=$1
commit_msg=$(cat $commit_msg_file)

pattern="^AP412695.*"

if ! [[ $commit_msg =~ $pattern ]]; then
    echo "Error: Commit message must start with 'AP412695'"
    exit 1
fi