- name: Ping all machines
  hosts: all
  tasks:
    - name: Ping machines
      ping:

- name: Copy inventory
  hosts: Endpoints
  tasks:
    - name: Copy
      copy:
        src: ~/MDO2024_INO/ITE/GCL4/LO410687/Sprawozdanie4/inventory.ini
        dest: ~/copied_inventory/inventory.ini
        remote_src: yes

    - name: Copy (again)
      copy:
        src: ~/MDO2024_INO/ITE/GCL4/LO410687/Sprawozdanie4/inventory.ini
        dest: ~/copied_inventory/inventory.ini

- name: Update package
  hosts: Endpoints
  vars:
    ansible_become: yes
    ansible_become_user: root
    ansible_become_pass: ansible # Password is ansible in this case
  tasks:
    - name: update
      apt:
        name: "*"
        state: latest
  
- name: Restart sshd and rngd
  hosts: Endpoints
  vars:
    ansible_become: yes
    ansible_become_user: root
    ansible_become_pass: ansible
  tasks:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
      
    - name: Restart rngd
      service:
        name: rngd
        state: restarted
