apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-stable
  labels:
    app: nginx-deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy1
      version: stable
  template:
    metadata:
      labels:
        app: nginx-deploy1
        version: stable
    spec:
      containers:
      - name: mynginx
        image: dankoo4/mynginx:v1
        ports:
        - containerPort: 80