- name: Zarządzanie kontenerem
  hosts: Endpoints
  tasks:
    - name: Pobieranie dockera
      become: true
      ansible.builtin.apt:
        name: docker.io
        state: latest
  
    - name: Umożliewienie jego dzialania bez reboota
      become: true
      command: systemctl enable --now docker

    - name: Pobieranie obrazu do zbudowania/do deployu programu
      copy:
        src: ~/zajecia/MDO2024_INO/INO/GCL1/JF412010/Sprawozdanie4/DEPLOY.Dockerfile
        dest: ~/node_app/Dockerfile

    - name: Budowanie obrazu.
      become: true
      community.docker.docker_image:
        name: deploy
        build:
          path: /home/ansible/node_app/
        source: build

    - name: Run container - and application in this
      become: true
      community.docker.docker_container:
        name: node_app
        image: deploy

    - name: Remove container
      become: true
      community.docker.docker_container:
        name: node_app
        state: absent
            
    
        