apiVersion: v1
kind: Service
metadata:
  name: temperature-converter-stable
spec:
  selector:
    app: temperature-converter
    tier: backend
    track: stable
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
