apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-recreate
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: weronikaabednarz/react-app:latest
          ports:
            - containerPort: 80
