- name: playbook1
  hosts: Endpoints
  vars:
    ansible_become_pass: ansible 
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Copy inventory
      copy:
        src: /home/jladz/MDO2024_INO/INO/GCL2/JL410406/Sprawozdanie4/inventory.ini
        dest: /home/ansible

    - name: Update packages
      become: yes
      apt:
        name: "*"
        state: latest

    - name: Restart sshd service
      become: yes
      service:
        name: sshd
        state: restarted

    - name: Restart rngd service
      become: yes
      service:
        name: rngd
        state: restarted
