---
# tasks file for install_and_run_docker
- name: Refresh all repositories
  command: zypper refresh
- name: Install Docker
  zypper:
    name: docker
    state: present
- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
- name: Copy files 2
  copy:
    src: "~/{{ item }}"
    dest: ~/
  with_items:
    - ghidra.zip
    - devops/MDO2024_INO/INO/GCL2/JK412625/Sprawozdanie4/Dockerfile
- name: Build Docker image
  docker_image:
    name: deploy
    build:
      path: /home/ansible
    source: build