#nalezy wpisac nazwe obrazu pierwszego kontenera 
FROM pomdog_build:jammy

#ustawienie katalogu roboczego
WORKDIR /pomdog/build/linux

#wskazanie ktora komenda ma zostac wywolana po uruchomieniu kontenera
CMD ["./test/pomdog_test"]
