- name: Install Docker
  hosts: Endpoints
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest
    
    - name: Install Docker
      dnf:
        name: docker
        state: latest
    
    - name: Start Docker
      command: systemctl enable --now docker

- name: Download & Manage Image
  hosts: Endpoints
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Check Volume
      command: docker volume inspect vol
      register: vol_exists
      failed_when: false
    
    - name: Create Volume
      command: docker volume create vol
      when: vol_exists is false

    - name: Get & Run
      docker_container:
        name: ansible_nginx
        image: nginx:latest
        state: started
        recreate: true
        volumes:
          - vol:/nginx
        ports:
          - "4444:80"

- name: Clean UP Docker
  hosts: Endpoints
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Stop & Remove
      docker_container:
        name: ansible_nginx
        state: absent
