pipeline {
    agent any
    
    
    
    stages {
        stage('Clean') {
            steps {
                echo 'Cleaning workspace'
                sh "rm -rf MDO2024_INO"
                sh 'docker system prune -f'
                sh "git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2024_INO.git"
                dir('MDO2024_INO') {
                    sh "git checkout KS409417"
                }
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building Docker imager'
                dir('MDO2024_INO/ITE/GCL4/KS409417/Sprawozdanie3') {
                    sh "docker build --no-cache -t node_builder:latest -f node_builder.Dockerfile . | tee -a ./build.log"

                }
            }
        }
        
        stage('Test') {
            steps {
                echo 'Building Test Docker image'
                dir('MDO2024_INO/ITE/GCL4/KS409417/Sprawozdanie3') {
                    sh "docker build --no-cache -t node_test:latest -f node_test.Dockerfile . | tee -a ./test.log"
                }
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying node'
                dir('MDO2024_INO/ITE/GCL4/KS409417/Sprawozdanie3') {
                    sh "docker build --no-cache -t node_deploy -f node_deploy.Dockerfile . | tee -a ./deploy.log"
                    sh "docker rmi node_builder:latest"
                    sh "docker rmi node_test:latest"
                }
            }
        }
        
        stage('Run') {
            steps {
                echo 'Running container'
                sh "docker images"
                sh "docker run -d node_deploy:latest"
            }
        }
        
        stage('Publish') {
            steps {
                echo "Publishing node to DockerHub"
                withCredentials([usernamePassword(credentialsId: '285bc673-b865-42d0-a921-fc013f4d4cf0', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "docker login -u $USERNAME -p $PASSWORD"
                    sh "docker tag node_deploy:latest ksagan23/node_deploy:latest"
                    sh "docker push ksagan23/node_deploy:latest"
                    echo 'Published!'
                }

            }
            post {
                always {
                    sh 'docker logout'
                }
            }
        }
    }
}