version: '3'

services:
  nodeapp_build:
    build:
      context: .
      dockerfile: ./nodeapp_builder.Dockerfile
    image: nodeapp_build

  nodeapp_test:
    build:
      context: .
      dockerfile: ./nodeapp_tester.Dockerfile
    image: nodeapp_test
    depends_on:
      - nodeapp_build

  nodeapp_depoy:
    build:
      context: .
      dockerfile: ./nodeapp_deploy.Dockerfile
    image: nodeapp_deploy
    depends_on:
      - nodeapp_build